#!/sbin/runscript
# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
	need net
}

start() {
	 ebegin "Stopping ${SVCNAME}"
	 start-stop-daemon --start --exec /usr/bin/omxoed \
	 	--background --make-pidfile \
	 	--pidfile /var/run/omeoed.pid
	eend $?
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --stop --exec /usr/bin/omxoed \
		--pidfile /var/run/omeoed.pid
	eend $?
}
