#!/sbin/runscript
# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

PIDFILE=/var/run/glusterd.pid

depend() {
	need net
}

start() {
	ebegin "Starting glusterd"
	start-stop-daemon --start -q --exec /usr/sbin/glusterd \
		--pidfile "${PIDFILE}" --make-pidfile --background \
		-- -N
	eend $?
}

stop() {
	ebegin "Stopping glusterd"
	start-stop-daemon --stop -q --pidfile "${PIDFILE}"
	eend $?
}
