--- Makefile.LINUX.orig	2006-10-06 02:50:55.000000000 +0200
+++ Makefile.LINUX	2006-10-06 02:52:30.000000000 +0200
@@ -1 +1,3 @@
+CXXFLAGS=""
+
 all : opj2dat liborigin.so
@@ -3,6 +5,6 @@
 liborigin.so : OPJFile.cpp OPJFile.h
-	g++ -shared -fPIC OPJFile.cpp -o liborigin.so
+	g++ $(CXXFLAGS) -shared -fPIC OPJFile.cpp -o liborigin.so
 
 opj2dat: opj2dat.cpp OPJFile.cpp
-	g++ -o opj2dat opj2dat.cpp OPJFile.cpp
+	g++ $(CXXFLAGS) -o opj2dat opj2dat.cpp OPJFile.cpp
 
