--- gffread-0.9.12/Makefile	2018-06-26 09:52:26.024747027 +0200
+++ gffread-0.9.12/Makefile	2018-06-26 09:52:41.845177021 +0200
@@ -1,4 +1,4 @@
-GCLDIR := ../gclib
+GCLDIR := ../gclib-0.10.2
 SEARCHDIRS := -I. -I${GCLDIR}
 
 SYSTYPE :=     $(shell uname)
@@ -10,7 +10,7 @@
     MARCH = 
 endif    
 
-CC      := g++
+CXX      ?= g++
 
 BASEFLAGS  := -Wall -Wextra ${SEARCHDIRS} $(MARCH) -D_FILE_OFFSET_BITS=64 \
 -D_LARGEFILE_SOURCE -D_REENTRANT -fno-strict-aliasing -fno-exceptions -fno-rtti
@@ -26,15 +26,17 @@
 GCC45OPTMAIN :=
 
 ifeq ($(findstring release,$(MAKECMDGOALS)),release)
-  CFLAGS := -O2 -DNDEBUG $(BASEFLAGS)
+  CXXFLAGS ?= -O2
+  CXXFLAGS += -DNDEBUG $(BASEFLAGS)
   LDFLAGS :=
 else
-  CFLAGS := -g -DDEBUG $(BASEFLAGS)
-  LDFLAGS := -g
+  CXXFLAGS ?= -g
+  CXXFLAGS += -DDEBUG $(BASEFLAGS)
+  LDFLAGS ?= -g
 endif
 
 %.o : %.cpp
-	${CC} ${CFLAGS} -c $< -o $@
+	${CXX} ${CXXFLAGS} -c $< -o $@
 
 # C/C++ linker
 
