# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.4

EAPI="2"

MODULE_AUTHOR="LDS"

inherit perl-module

DESCRIPTION="Bio::DB::Sam -- Read SAM/BAM database files"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

DEPEND=">=sci-biology/bioperl-1.6.901
	virtual/perl-Module-Build
	dev-lang/perl
	>=sci-biology/samtools-0.1.16"

RDEPEND="${DEPEND}"

src_prepare(){
	sed -i s'#HeaderFile = "bam.h#HeaderFile = "bam/bam.h#' "${WORKDIR}"/"${P}"/Build.PL || die "Failed to fix bam.h to bam/bam.h in Build.PL"
	sed -i s'#include "bam.h#include "bam/bam.h#' "${WORKDIR}"/"${P}"/lib/Bio/DB/Sam.xs || die "Failed to fix bam.h to bam/bam.h in lib/Bio/DB/Sam.xs"
	sed -i s'#include "khash.h#include "bam/khash.h#' "${WORKDIR}"/"${P}"/lib/Bio/DB/Sam.xs || die "Failed to fix khash.h to bam/khash.h in lib/Bio/DB/Sam.xs"
	sed -i s'#include "faidx.h#include "bam/faidx.h#' "${WORKDIR}"/"${P}"/lib/Bio/DB/Sam.xs || die "Failed to fix faidx.h to bam/faidx.h in lib/Bio/DB/Sam.xs"
}
