--- src/Makefile.am	2008-06-06 01:15:31.000000000 +0200
+++ src/Makefile.am.new	2009-08-22 22:38:00.000000000 +0200
@@ -1,3 +1,3 @@
 #SUBDIRS =  #io param pdb molecules util moveset system forcefield zeta mpi dcdtools analysis modules  tests
 
-SUBDIRS= lib tinyxml libxml   forcefield  examples tests
+SUBDIRS= lib forcefield  examples tests
--- src/lib/Makefile.am	2008-07-17 17:57:14.000000000 +0200
+++ src/lib/Makefile.am.new	2009-08-23 20:45:00.000000000 +0200
@@ -1,6 +1,7 @@
 INCLUDES = -I../../include/almost -I../rose -I../zeta/ -Imodules
 SUBDIRS=modules
 lib_LIBRARIES=libAlm.a
+libAlm_la_LIBADD=libboost_iostreams.a
 REGEXSOURCES=	regex/c_regex_traits.cpp   \
 		regex/cpp_regex_traits.cpp \
 		regex/cregex.cpp \
@@ -19,15 +20,6 @@
 		regex/wide_posix_api.cpp \
 		regex/winstances.cpp
 
-IOSTREAMSSOURCES = iostreams/bzip2.cpp \
-		iostreams/file_descriptor.cpp \
-		iostreams/mapped_file.cpp \
-		iostreams/zlib.cpp
-
-IOSOURCES        = io/formostream.cpp
-
-
-
 PBDSOURCES = 	pdb/pdbatomline.cpp \
 		pdb/pdbauthorline.cpp \
 		pdb/pdbcompndline.cpp \
@@ -208,8 +200,8 @@
 
 
 
-nodist_libAlm_a_SOURCES= $(REGEXSOURCES) $(PBDSOURCES) $(IOSTREAMSSOURCES) \
-		$(IOSOURCES) $(MDBSOUCES) $(MOLECULESSOURCES) \
+nodist_libAlm_a_SOURCES= $(REGEXSOURCES) $(PBDSOURCES) \
+		$(MDBSOUCES) $(MOLECULESSOURCES) \
 		$(MOVESETSOURCES) $(DCDTOOLSSOURCES) $(ALGOSOURCES) \
 		$(MODSOURCES) $(CODE) $(ZETASOURCES) $(CHESHIRESOURCES)
 
