--- Makefile.ori	2017-04-06 23:38:08.591353594 +0200
+++ Makefile	2017-04-06 23:41:34.127107768 +0200
@@ -1,12 +1,12 @@
-Cxx = g++
+CXX ?= g++
 
 
-CFLAGS = -O3 
-LFLAGS=  -lz
+CXXFLAGS ?= -O3
+LFLAGS = -lz
 
 all: mergeReads nxtrim
 
-debug: CFLAGS = -Wall -g 
+debug: CXXFLAGS += -Wall -g
 debug: all
 
 GIT_HASH := $(shell git describe --abbrev=4 --always )
@@ -21,17 +21,17 @@
 
 
 unit_test: test.cpp fastqlib.o utilityfunc.o matepair.o
-	$(CXX) $(CFLAGS) test.cpp fastqlib.o utilityfunc.o matepair.o -o unit_test   $(LFLAGS)
+	$(CXX) $(CXXFLAGS) test.cpp fastqlib.o utilityfunc.o matepair.o -o unit_test   $(LFLAGS)
 nxtrim: nxtrim.cpp fastqlib.o utilityfunc.o matepair.o fastqlib.o version.h
-	$(CXX) $(CFLAGS) nxtrim.cpp fastqlib.o utilityfunc.o matepair.o -o nxtrim  $(LFLAGS)
+	$(CXX) $(CXXFLAGS) nxtrim.cpp fastqlib.o utilityfunc.o matepair.o -o nxtrim  $(LFLAGS)
 mergeReads: mergeReads.cpp fastqlib.o utilityfunc.o fastqlib.o githash.h version.h
-	$(CXX) $(CFLAGS)  mergeReads.cpp fastqlib.o utilityfunc.o -o mergeReads   $(LFLAGS)
+	$(CXX) $(CXXFLAGS)  mergeReads.cpp fastqlib.o utilityfunc.o -o mergeReads   $(LFLAGS)
 matepair.o: matepair.cpp matepair.h fastqlib.h
-	$(CXX) $(CFLAGS) -c matepair.cpp
+	$(CXX) $(CXXFLAGS) -c matepair.cpp
 fastqlib.o: fastqlib.cpp fastqlib.h utilityfunc.h
-	$(CXX) $(CFLAGS) -c fastqlib.cpp
+	$(CXX) $(CXXFLAGS) -c fastqlib.cpp
 utilityfunc.o:  utilityfunc.cpp utilityfunc.h
-	$(CXX) $(CFLAGS) -c utilityfunc.cpp 
+	$(CXX) $(CXXFLAGS) -c utilityfunc.cpp
 test: nxtrim
 	bash example/run_test.sh
 clean:
