--- Makefile	2009-03-02 22:42:03.000000000 +0100
+++ Makefile.new	2009-03-02 22:41:55.000000000 +0100
@@ -288,13 +288,13 @@
 #
 # Program to use to decompress a data file
 #
-DECOMPRESS = /usr/bin/bunzip2
+DECOMPRESS = /bin/bunzip2
 
 
 #
 # Program to use to compress a data file
 #
-COMPRESS = /usr/bin/bzip2
+COMPRESS = /bin/bzip2
 
 #
 # Program to use to generate a signature
@@ -330,12 +330,12 @@
 #########################################################
 CC	= gcc
 C++	= g++
-CFLAGS  = -g -O2  -Wall -ansi -pedantic
+CFLAGS  += -ansi -D_POSIX_SOURCE
 F90C = gfortran
-F90FLAGS = -g
+F90FLAGS += -fno-range-check
 F90LDFLAGS = 
 M4FLAGS = -Dfcb_bytes_in_rec=131072
-TIME = time
+# TIME = time
 
 ifneq ($(NOFORTRAN),)
 F90C =
@@ -357,7 +357,7 @@
 DATADIRI  = $(ROOT)/../CBFlib_$(VERSION)_Data_Files_Input
 DATADIRO  = $(ROOT)/../CBFlib_$(VERSION)_Data_Files_Output
 DATADIRS  = $(ROOT)/../CBFlib_$(VERSION)_Data_Files_Output_Sigs_Only
-INSTALLDIR  = $(HOME)
+INSTALLDIR  = $(DESTDIR)/usr
 
 #
 # URLs from which to retrieve the data directories
@@ -667,7 +667,6 @@
 		-cp $(INSTALLDIR)/bin/testflatpacked $(INSTALLDIR)/bin/testflatpacked_old
 		cp $(BIN)/testflatpacked $(INSTALLDIR)/bin/testflatpacked
 		-rm -rf $(INSTALLDIR)/include/cbflib_old
-		-cp -r $(INSTALLDIR)/include/cbflib $(INSTALLDIR)/include/cbflib_old
 		-rm -rf $(INSTALLDIR)/include/cbflib
 		cp -r $(INCLUDE) $(INSTALLDIR)/include/cbflib
 		chmod 644 $(INSTALLDIR)/lib/libcbf.a
@@ -681,6 +680,7 @@
 		chmod 755 $(INSTALLDIR)/bin/testflat
 		chmod 755 $(INSTALLDIR)/bin/testflatpacked
 		chmod -R 644 $(INSTALLDIR)/include/cbflib
+		chmod 775 $(INSTALLDIR)/include/cbflib
 		
 		
 #
--- Makefile	2009-03-06 15:04:55.338223367 +0100
+++ Makefile.new	2009-03-06 15:05:04.591555828 +0100
@@ -839,7 +839,7 @@
 #
 $(BIN)/convert_image: $(LIB)/libcbf.a $(EXAMPLES)/convert_image.c $(EXAMPLES)/img.c \
 					$(GOPTLIB)	$(GOPTINC)
-	$(CC) $(CFLAGS) $(INCLUDES) $(WARNINGS) \
+	$(CC) $(CFLAGS) $(LDFLAGS) $(INCLUDES) $(WARNINGS) \
               $(EXAMPLES)/convert_image.c $(EXAMPLES)/img.c $(GOPTLIB) -L$(LIB) \
 	      -lcbf -lm -o $@
 #
@@ -847,7 +847,7 @@
 #
 $(BIN)/convert_minicbf: $(LIB)/libcbf.a $(EXAMPLES)/convert_minicbf.c \
 					$(GOPTLIB)	$(GOPTINC)
-	$(CC) $(CFLAGS) $(INCLUDES) $(WARNINGS) \
+	$(CC) $(CFLAGS) $(LDFLAGS) $(INCLUDES) $(WARNINGS) \
               $(EXAMPLES)/convert_minicbf.c $(GOPTLIB) -L$(LIB) \
 	      -lcbf -lm -o $@
 
@@ -855,7 +855,7 @@
 # makecbf example program
 #
 $(BIN)/makecbf: $(LIB)/libcbf.a $(EXAMPLES)/makecbf.c $(LIB)/libimg.a
-	$(CC) $(CFLAGS) $(INCLUDES) $(WARNINGS) \
+	$(CC) $(CFLAGS) $(LDFLAGS) $(INCLUDES) $(WARNINGS) \
               $(EXAMPLES)/makecbf.c  -L$(LIB) \
 	      -lcbf -lm -limg -o $@
 
@@ -864,7 +864,7 @@
 # adscimg2cbf example program
 #
 $(BIN)/adscimg2cbf: $(LIB)/libcbf.a $(EXAMPLES)/adscimg2cbf.c $(EXAMPLES)/adscimg2cbf_sub.c
-	$(CC) $(CFLAGS) -D_SVID_SOURCE $(INCLUDES) $(WARNINGS) \
+	$(CC) $(CFLAGS) $(LDFLAGS) -D_SVID_SOURCE $(INCLUDES) $(WARNINGS) \
               $(EXAMPLES)/adscimg2cbf.c $(EXAMPLES)/adscimg2cbf_sub.c  -L$(LIB) \
 	      -lcbf -lm -o $@
 
@@ -872,7 +872,7 @@
 # cbf2adscimg example program
 #
 $(BIN)/cbf2adscimg: $(LIB)/libcbf.a $(EXAMPLES)/cbf2adscimg.c $(EXAMPLES)/cbf2adscimg_sub.c
-	$(CC) $(CFLAGS) -D_SVID_SOURCE $(INCLUDES) $(WARNINGS) \
+	$(CC) $(CFLAGS) $(LDFLAGS) -D_SVID_SOURCE $(INCLUDES) $(WARNINGS) \
 		      $(EXAMPLES)/cbf2adscimg.c $(EXAMPLES)/cbf2adscimg_sub.c  -L$(LIB) \
 		  -lcbf -lm -o $@
 
@@ -881,7 +881,7 @@
 #
 $(BIN)/img2cif: $(LIB)/libcbf.a $(EXAMPLES)/img2cif.c $(LIB)/libimg.a \
 					$(GOPTLIB) 	$(GOTPINC)
-	$(CC) $(CFLAGS) $(INCLUDES) $(WARNINGS) \
+	$(CC) $(CFLAGS) $(LDFLAGS) $(INCLUDES) $(WARNINGS) \
               $(EXAMPLES)/img2cif.c $(GOPTLIB) -L$(LIB) \
 	      -lcbf -lm -limg -o $@
 
@@ -890,14 +890,14 @@
 #
 $(BIN)/cif2cbf: $(LIB)/libcbf.a $(EXAMPLES)/cif2cbf.c $(LIB)/libimg.a \
 					$(GOPTLIB)	$(GOPTINC)
-	$(CC) $(CFLAGS) $(INCLUDES) $(WARNINGS) \
+	$(CC) $(CFLAGS) $(LDFLAGS) $(INCLUDES) $(WARNINGS) \
               $(EXAMPLES)/cif2cbf.c $(GOPTLIB) -L$(LIB) \
 	      -lcbf -lm -limg -o $@
 #
 # testcell example program
 #
 $(BIN)/testcell: $(LIB)/libcbf.a $(EXAMPLES)/testcell.C
-	$(C++) $(CFLAGS) $(INCLUDES) $(WARNINGS) \
+	$(C++) $(CFLAGS) $(LDFLAGS) $(INCLUDES) $(WARNINGS) \
               $(EXAMPLES)/testcell.C -L$(LIB) \
 	      -lcbf -lm -o $@
 
@@ -905,7 +905,7 @@
 # cif2c example program
 #
 $(BIN)/cif2c: $(LIB)/libcbf.a $(EXAMPLES)/cif2c.c
-	$(C++) $(CFLAGS) $(INCLUDES) $(WARNINGS) \
+	$(C++) $(CFLAGS) $(LDFLAGS) $(INCLUDES) $(WARNINGS) \
               $(EXAMPLES)/cif2c.c -L$(LIB) \
 	      -lcbf -lm -o $@
 
@@ -913,7 +913,7 @@
 # sauter_test example program
 #
 $(BIN)/sauter_test: $(LIB)/libcbf.a $(EXAMPLES)/sauter_test.C
-	$(C++) $(CFLAGS) $(INCLUDES) $(WARNINGS) \
+	$(C++) $(CFLAGS) $(LDFLAGS) $(INCLUDES) $(WARNINGS) \
               $(EXAMPLES)/sauter_test.C -L$(LIB) \
 	      -lcbf -lm -o $@
 
@@ -921,21 +921,21 @@
 # testreals example program
 #
 $(BIN)/testreals: $(LIB)/libcbf.a $(EXAMPLES)/testreals.c
-	$(CC) $(CFLAGS) $(INCLUDES) $(WARNINGS) \
+	$(CC) $(CFLAGS) $(LDFLAGS) $(INCLUDES) $(WARNINGS) \
               $(EXAMPLES)/testreals.c -L$(LIB) \
 	      -lcbf -lm -o $@
 #
 # testflat example program
 #
 $(BIN)/testflat: $(LIB)/libcbf.a $(EXAMPLES)/testflat.c
-	$(CC) $(CFLAGS) $(INCLUDES) $(WARNINGS) \
+	$(CC) $(CFLAGS) $(LDFLAGS) $(INCLUDES) $(WARNINGS) \
               $(EXAMPLES)/testflat.c -L$(LIB) \
 	      -lcbf -lm -o $@
 #
 # testflatpacked example program
 #
 $(BIN)/testflatpacked: $(LIB)/libcbf.a $(EXAMPLES)/testflatpacked.c
-	$(CC) $(CFLAGS) $(INCLUDES) $(WARNINGS) \
+	$(CC) $(CFLAGS) $(LDFLAGS) $(INCLUDES) $(WARNINGS) \
               $(EXAMPLES)/testflatpacked.c -L$(LIB) \
 	      -lcbf -lm -o $@
 	      
--- getopt-1.1.4_cbf/Makefile   2007-11-17 04:41:43.000000000 +0100
+++ getopt-1.1.4_cbf/Makefile.new       2009-03-02 23:03:35.000000000 +0100
@@ -44,7 +44,7 @@
          -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes \
          -Wnested-externs -Winline
 OPTIMIZE=-O3 -fno-strength-reduce
-CFLAGS=$(WARNINGS) $(OPTIMIZE)
+CFLAGS += -fno-strength-reduce
 LDFLAGS=
 
 sources=getopt.c


